import type { GameDataResourceKey } from '../../services/game-data';

/**
 * 没有 name/code 的资料表默认展示字段。
 *
 * 这些配置只服务于跨表引用展示；普通表格列仍由各页面自己的 fields 维护。
 */
export const gameDataDisplayFields: Partial<Record<GameDataResourceKey, string[]>> = {
  'ability-details': ['ability_id', 'short_effect'],
  'advanced-contest-effect-skills': ['advanced_contest_effect_id', 'skill_id'],
  'advanced-contest-effects': ['flavor_text', 'appeal'],
  'berry-flavor-potencies': ['berry_id', 'flavor_id', 'potency'],
  'catalog-entries': ['catalog_id', 'species_id', 'entry_number'],
  'characteristic-values': ['characteristic_id', 'possible_value'],
  'contest-effects': ['effect', 'appeal'],
  'creature-abilities': ['creature_id', 'ability_id', 'slot_order'],
  'creature-elements': ['creature_id', 'element_id', 'slot_order'],
  'creature-form-elements': ['form_id', 'element_id', 'slot_order'],
  'creature-game-indices': ['creature_id', 'game_index'],
  'creature-held-items': ['creature_id', 'item_id'],
  'creature-skill-learns': ['creature_id', 'skill_id'],
  'creature-stats': ['creature_id', 'stat_id', 'base_value'],
  'element-damage-relations': ['source_element_id', 'target_element_id', 'relation_type'],
  'element-game-indices': ['element_id', 'game_index'],
  'event-stat-nature-effects': ['event_stat_id', 'nature_id', 'effect_type'],
  'evolution-chains': ['baby_trigger_item_id'],
  'evolution-details': ['from_species_id', 'to_species_id', 'trigger_id'],
  'evolution-nodes': ['chain_id', 'species_id', 'parent_species_id'],
  'gender-evolution-requirements': ['gender_id', 'species_id'],
  'gender-species-rates': ['gender_id', 'species_id', 'rate'],
  'growth-rate-levels': ['growth_rate_id', 'level', 'experience'],
  'item-attribute-bindings': ['item_id', 'attribute_id'],
  'item-category-pockets': ['category_id', 'pocket_id'],
  'item-details': ['item_id', 'short_effect'],
  'item-game-indices': ['item_id', 'game_index'],
  'location-area-encounter-condition-values': ['encounter_id', 'condition_value_id'],
  'location-area-encounters': ['area_id', 'creature_id', 'method_id', 'min_level', 'max_level'],
  'location-area-method-rates': ['area_id', 'method_id', 'rate'],
  'location-game-indices': ['location_id', 'game_index'],
  machines: ['item_id', 'skill_id'],
  'nature-battle-style-preferences': ['nature_id', 'battle_style_id'],
  'nature-event-stat-changes': ['nature_id', 'event_stat_id', 'max_change'],
  'skill-contest-combos': ['skill_id', 'combo_type', 'related_skill_id'],
  'skill-details': ['skill_id', 'short_effect'],
  'skill-stat-changes': ['skill_id', 'stat_id', 'change_value'],
  'species-catalog-numbers': ['species_id', 'catalog_id', 'entry_number'],
  'species-creature-varieties': ['species_id', 'creature_id'],
  'species-details': ['species_id', 'genus'],
  'species-egg-groups': ['species_id', 'egg_group_id'],
  'stat-characteristics': ['stat_id', 'characteristic_id'],
  'stat-nature-effects': ['stat_id', 'nature_id', 'effect_type'],
  'stat-skill-effects': ['stat_id', 'skill_id', 'change_value'],
  'transfer-area-species': ['area_id', 'species_id', 'rate'],
};
