import type { RouteMeta } from '../../app/layout/menu';

export const battleRulesRouteMetas: RouteMeta[] = [
  {
    path: '/battle-rules/coverage',
    title: '规则覆盖',
    componentKey: 'battle-rules/coverage',
    accessCode: 'battle-rules.coverage',
  },
  {
    path: '/battle-rules/battle-formats',
    title: '战斗赛制',
    componentKey: 'battle-rules/battle-formats',
    accessCode: 'battle-rules.battle-formats',
  },
  {
    path: '/battle-rules/format-clauses',
    title: '赛制条款',
    componentKey: 'battle-rules/format-clauses',
    accessCode: 'battle-rules.format-clauses',
  },
  {
    path: '/battle-rules/format-clause-bindings',
    title: '赛制条款绑定',
    componentKey: 'battle-rules/format-clause-bindings',
    accessCode: 'battle-rules.format-clause-bindings',
  },
  {
    path: '/battle-rules/format-restrictions',
    title: '赛制限制',
    componentKey: 'battle-rules/format-restrictions',
    accessCode: 'battle-rules.format-restrictions',
  },
  {
    path: '/battle-rules/preparation-validation',
    title: '准备校验',
    componentKey: 'battle-rules/preparation-validation',
    accessCode: 'battle-rules.preparation-validation',
  },
  {
    path: '/battle-rules/action-validation',
    title: '行动校验',
    componentKey: 'battle-rules/action-validation',
    accessCode: 'battle-rules.action-validation',
  },
  {
    path: '/battle-rules/special-mechanics',
    title: '特殊机制',
    componentKey: 'battle-rules/special-mechanics',
    accessCode: 'battle-rules.special-mechanics',
  },
  {
    path: '/battle-rules/format-special-mechanics',
    title: '赛制特殊机制',
    componentKey: 'battle-rules/format-special-mechanics',
    accessCode: 'battle-rules.format-special-mechanics',
  },
  {
    path: '/battle-rules/status-rules',
    title: '状态规则',
    componentKey: 'battle-rules/status-rules',
    accessCode: 'battle-rules.status-rules',
  },
  {
    path: '/battle-rules/weather-rules',
    title: '天气规则',
    componentKey: 'battle-rules/weather-rules',
    accessCode: 'battle-rules.weather-rules',
  },
  {
    path: '/battle-rules/terrain-rules',
    title: '场地规则',
    componentKey: 'battle-rules/terrain-rules',
    accessCode: 'battle-rules.terrain-rules',
  },
  {
    path: '/battle-rules/field-rules',
    title: '场上效果',
    componentKey: 'battle-rules/field-rules',
    accessCode: 'battle-rules.field-rules',
  },
  {
    path: '/battle-rules/skill-rules',
    title: '技能规则',
    componentKey: 'battle-rules/skill-rules',
    accessCode: 'battle-rules.skill-rules',
  },
  {
    path: '/battle-rules/skill-status-effects',
    title: '技能状态效果',
    componentKey: 'battle-rules/skill-status-effects',
    accessCode: 'battle-rules.skill-status-effects',
  },
  {
    path: '/battle-rules/skill-stat-stage-effects',
    title: '技能能力阶级效果',
    componentKey: 'battle-rules/skill-stat-stage-effects',
    accessCode: 'battle-rules.skill-stat-stage-effects',
  },
  {
    path: '/battle-rules/skill-stat-stage-operations',
    title: '技能能力阶级操作',
    componentKey: 'battle-rules/skill-stat-stage-operations',
    accessCode: 'battle-rules.skill-stat-stage-operations',
  },
  {
    path: '/battle-rules/skill-field-effects',
    title: '技能场上效果',
    componentKey: 'battle-rules/skill-field-effects',
    accessCode: 'battle-rules.skill-field-effects',
  },
  {
    path: '/battle-rules/skill-global-field-effects',
    title: '技能全场效果',
    componentKey: 'battle-rules/skill-global-field-effects',
    accessCode: 'battle-rules.skill-global-field-effects',
  },
  {
    path: '/battle-rules/skill-weather-accuracy-overrides',
    title: '技能天气命中',
    componentKey: 'battle-rules/skill-weather-accuracy-overrides',
    accessCode: 'battle-rules.skill-weather-accuracy-overrides',
  },
  {
    path: '/battle-rules/skill-weather-power-modifiers',
    title: '技能天气威力',
    componentKey: 'battle-rules/skill-weather-power-modifiers',
    accessCode: 'battle-rules.skill-weather-power-modifiers',
  },
  {
    path: '/battle-rules/skill-weather-element-overrides',
    title: '技能天气属性',
    componentKey: 'battle-rules/skill-weather-element-overrides',
    accessCode: 'battle-rules.skill-weather-element-overrides',
  },
  {
    path: '/battle-rules/skill-charge-skip-weathers',
    title: '技能蓄力天气',
    componentKey: 'battle-rules/skill-charge-skip-weathers',
    accessCode: 'battle-rules.skill-charge-skip-weathers',
  },
  {
    path: '/battle-rules/ability-rules',
    title: '特性规则',
    componentKey: 'battle-rules/ability-rules',
    accessCode: 'battle-rules.ability-rules',
  },
  {
    path: '/battle-rules/item-rules',
    title: '道具规则',
    componentKey: 'battle-rules/item-rules',
    accessCode: 'battle-rules.item-rules',
  },
];
