import type { ReactNode } from 'react';

const menuIconClasses = {
  'lucide:settings': 'icon-[lucide--settings]',
  'lucide:shield-check': 'icon-[lucide--shield-check]',
  'lucide:users': 'icon-[lucide--users]',
  'lucide:shield-user': 'icon-[lucide--shield-user]',
  'lucide:network': 'icon-[lucide--network]',
  'lucide:key-round': 'icon-[lucide--key-round]',
  'lucide:plug': 'icon-[lucide--plug]',
  'lucide:key': 'icon-[lucide--key]',
  'lucide:calendar-clock': 'icon-[lucide--calendar-clock]',
  'lucide:clock': 'icon-[lucide--clock]',
  'lucide:database': 'icon-[lucide--database]',
  'lucide:boxes': 'icon-[lucide--boxes]',
  'lucide:badge': 'icon-[lucide--badge]',
  'lucide:tags': 'icon-[lucide--tags]',
  'lucide:sparkles': 'icon-[lucide--sparkles]',
  'lucide:badge-check': 'icon-[lucide--badge-check]',
  'lucide:package': 'icon-[lucide--package]',
  'lucide:list-tree': 'icon-[lucide--list-tree]',
  'lucide:layout-list': 'icon-[lucide--layout-list]',
  'lucide:cloud-sun': 'icon-[lucide--cloud-sun]',
  'lucide:land-plot': 'icon-[lucide--land-plot]',
  'lucide:ban': 'icon-[lucide--ban]',
  'lucide:shield': 'icon-[lucide--shield]',
  'lucide:flame': 'icon-[lucide--flame]',
  'lucide:chart-no-axes-column': 'icon-[lucide--chart-no-axes-column]',
  'lucide:split': 'icon-[lucide--split]',
  'lucide:folder-tree': 'icon-[lucide--folder-tree]',
  'lucide:palette': 'icon-[lucide--palette]',
  'lucide:shapes': 'icon-[lucide--shapes]',
  'lucide:map': 'icon-[lucide--map]',
  'lucide:layers-3': 'icon-[lucide--layers-3]',
  'lucide:git-branch': 'icon-[lucide--git-branch]',
  'lucide:activity': 'icon-[lucide--activity]',
  'lucide:badge-info': 'icon-[lucide--badge-info]',
  'lucide:book-open': 'icon-[lucide--book-open]',
  'lucide:briefcase': 'icon-[lucide--briefcase]',
  'lucide:candy': 'icon-[lucide--candy]',
  'lucide:chart-column': 'icon-[lucide--chart-column]',
  'lucide:cherry': 'icon-[lucide--cherry]',
  'lucide:crosshair': 'icon-[lucide--crosshair]',
  'lucide:disc-3': 'icon-[lucide--disc-3]',
  'lucide:file-text': 'icon-[lucide--file-text]',
  'lucide:filter': 'icon-[lucide--filter]',
  'lucide:fingerprint': 'icon-[lucide--fingerprint]',
  'lucide:folders': 'icon-[lucide--folders]',
  'lucide:footprints': 'icon-[lucide--footprints]',
  'lucide:gauge': 'icon-[lucide--gauge]',
  'lucide:git-fork': 'icon-[lucide--git-fork]',
  'lucide:globe-2': 'icon-[lucide--globe-2]',
  'lucide:graduation-cap': 'icon-[lucide--graduation-cap]',
  'lucide:hash': 'icon-[lucide--hash]',
  'lucide:layers': 'icon-[lucide--layers]',
  'lucide:list-checks': 'icon-[lucide--list-checks]',
  'lucide:list-ordered': 'icon-[lucide--list-ordered]',
  'lucide:map-pin': 'icon-[lucide--map-pin]',
  'lucide:map-pinned': 'icon-[lucide--map-pinned]',
  'lucide:package-search': 'icon-[lucide--package-search]',
  'lucide:percent': 'icon-[lucide--percent]',
  'lucide:radar': 'icon-[lucide--radar]',
  'lucide:route': 'icon-[lucide--route]',
  'lucide:send': 'icon-[lucide--send]',
  'lucide:smile': 'icon-[lucide--smile]',
  'lucide:swords': 'icon-[lucide--swords]',
  'lucide:table-2': 'icon-[lucide--table-2]',
  'lucide:tag': 'icon-[lucide--tag]',
  'lucide:trees': 'icon-[lucide--trees]',
  'lucide:trending-up': 'icon-[lucide--trending-up]',
  'lucide:trophy': 'icon-[lucide--trophy]',
  'lucide:venus-and-mars': 'icon-[lucide--venus-and-mars]',
  'lucide:workflow': 'icon-[lucide--workflow]',
  'lucide:zap': 'icon-[lucide--zap]',
  'lucide:star': 'icon-[lucide--star]',
} as const;

export function resolveMenuIcon(icon?: string): ReactNode {
  const iconClass = icon ? menuIconClasses[icon as keyof typeof menuIconClasses] : undefined;
  if (!iconClass) {
    return undefined;
  }

  return <span aria-hidden="true" className={`${iconClass} text-base`} />;
}
